AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  metafy-sam

  Serverless Application for deployment of the Metafy project.

Parameters:
  EnvType:
    Description: Environment Type
    Default: test
    Type: String
    AllowedValues:
      - prod
      - test
    ConstraintDescription: Please choose either 'prod' or 'test'
  SpotifyClientID:
    Type: String
    Default: OVERRIDE_ME
    Description: Override with Spotify Client ID
  SpotifyClientSecret:
    Type: String
    Default: OVERRIDE_ME
    Description: Override with Spotify Client Secret
  SpotifyRefToken:
    Type: String
    Default: OVERRIDE_ME
    Description: Override with Spotify Refresh Token
  SpotifyPlaylistID:
    Type: String
    Default: OVERRIDE_ME
    Description: Override with the Spotify URI of the Playlist you've authorized Metafy to modify

Resources:
  MetafyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: metafy/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 20
      Environment:
        Variables:
          ENVIRONMENT_TYPE: !Ref EnvType
      Events:
        Mondays:
          Type: Schedule
          Properties:
            Schedule: cron(0 8 ? * MON *)
            Name: EveryMondayAt8AM
            Enabled: True

Outputs:
  MetafyLambdaFunction:
    Description: "The ARN of the Metafy Lambda Function"
    Value: !GetAtt MetafyLambdaFunction.Arn
